services:
  app:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "$PORT:$PORT"
    env_file:
      - .env
    # command: bash -c "npx prisma migrate deploy && npx prisma generate && npx prisma db seed && yarn build && yarn start"
    command: bash -c "npx prisma migrate deploy && npx prisma generate && yarn build && yarn start"
    # command: bash -c "yarn start"
    networks:
      - easy-home-network
    depends_on:
      - db
  db:
    image: postgis/postgis:14-3.4
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - easy-home-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  postgres-data:
    driver: local
networks:
  easy-home-network:
